可以在子组件树的任何位置捕获 JavaScript 错误，记录这些错误，并显示一个备用 UI ，而不是使整个组件树崩溃

class 组件中定义了 getDerivedStateFromError 或 componentDidCatch 这两个生命周期方法中的任意一个（或两个）时，就变成一个错误边界

- componentDidCatch：该生命周期在 fiber 更新流程的 commit 阶段发生，可以处理副作用，可以调用 setState、上报错误日志

- getDerivedStateFromError：是个静态方法，返回值可以合并到 state 中用于控制渲染错误时需要显示的 ui

示例如下

```js
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(error) {
    return { hasError: true };
  }

  componentDidCatch(error, errorInfo) {
    // 上报错误日志
    logErrorToMyService(error, errorInfo);
  }

  render() {
    if (this.state.hasError) {
      return <h1>Something went wrong.</h1>;
    }

    return this.props.children;
  }
}
```

然后将需要进行错误捕获的组件包裹起来

```js
<ErrorBoundary>
    <AppMain/>
<ErrorBoundary/>
```

错误边界有以下特性

- 错误边界类似于 javascript 中的 catch {...}，不同的是只针对 react 组件
- 子组件的错误会冒泡至最近的上层错误边界
- 16 版本后，任何未被错误边界捕获的错误将会导致整个 React 组件树被卸载，防止错误的 UI 对用户产生误导

一些错误无法捕获到

- 事件处理，捕获错误可以使用 try...catch...
- 异步代码
- 服务端渲染
- 只能捕获子组件的错误，无法捕获自己的错误
